services:
  - type: web
    name: sistema-5s-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0

  - type: web
    name: sistema-5s-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://sistema-5s-backend.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
